// Reads the icons listed in icon-list.mjs and generates:
//   apps/web/public/icons/sprite.svg           — served by web app
//   apps/landing/public/icons/sprite.svg       — served by landing app
//   packages/ui/components/icon/icon-names.ts  — IconName union type

import * as fs from "node:fs";
import * as fsp from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { lucideIconList } from "../components/icon/icon-list.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "../../..");

const lucideIconsDir = path.join(root, "node_modules/lucide-static/icons");
const typeOutputPath = path.join(root, "packages/ui/components/icon/icon-names.ts");
const spritePublicDirs = [
  path.join(root, "apps/web/public/icons"),
  path.join(root, "apps/landing/public/icons"),
];

// Match the stroke weight the previous hand-built sprite used, so icons keep
// their existing look (lucide ships at stroke-width 2).
const STROKE_WIDTH = "1.5";

function buildSymbol(name) {
  const svgPath = path.join(lucideIconsDir, `${name}.svg`);
  if (!fs.existsSync(svgPath)) {
    throw new Error(
      `Icon "${name}" not found in lucide-static (${svgPath}). Check the name in icon-list.mjs.`
    );
  }

  const source = fs.readFileSync(svgPath, "utf8");
  const inner = source
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<svg[^>]*>/, "")
    .replace(/<\/svg>/, "")
    .trim();

  return [
    `  <symbol id="${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" stroke-linejoin="round">`,
    `    ${inner.replace(/\n/g, "\n    ")}`,
    `  </symbol>`,
  ].join("\n");
}

function buildSprite(names) {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- This file is generated by npm run build:icons -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">`,
    `<defs>`,
    ...names.map(buildSymbol),
    `</defs>`,
    `</svg>`,
    "",
  ].join("\n");
}

function buildTypes(names) {
  const union = names.map((name) => `  | "${name}"`).join("\n");
  return `// This file is generated by npm run build:icons\n\nexport type IconName =\n${union};\n`;
}

async function main() {
  const names = [...lucideIconList].sort();
  if (names.length === 0) {
    console.error("icon-list.mjs is empty — add icon names.");
    process.exit(1);
  }

  const sprite = buildSprite(names);
  const types = buildTypes(names);

  await fsp.mkdir(path.dirname(typeOutputPath), { recursive: true });
  await fsp.writeFile(typeOutputPath, types, "utf8");
  for (const dir of spritePublicDirs) {
    await fsp.mkdir(dir, { recursive: true });
    await fsp.writeFile(path.join(dir, "sprite.svg"), sprite, "utf8");
  }

  console.log(`Generated ${names.length} icons → sprite.svg (x2) + icon-names.ts`);
}

await main();
