// This file is generated by npm run build:icons

export type IconName =
  | "alert-triangle"
  | "check"
  | "chevron-left"
  | "chevron-right"
  | "eye"
  | "eye-off"
  | "refresh-cw"
  | "search"
  | "users"
  | "x";
